/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: df86e243cf563a70175a2ae7bfb67896)
// NOTE: wrangler infers a string-literal type from each var's `wrangler.jsonc` default value —
// widened to `string` by hand since these vary per environment (see env.ts).
interface __BaseEnv_Env {
  MEDIA: R2Bucket;
  MEDIA_BASE_URL: string;
  MEDIA_UPLOAD_SECRET: string;
  GAME_ROOM: DurableObjectNamespace<import('./index').GameRoom>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
    durableNamespaces: 'GameRoom';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
