/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: fbcf05860efd45375185059e78803a53)
interface __BaseEnv_Env {
  MEDIA: R2Bucket;
  GAME_ROOM: DurableObjectNamespace<import('./index').GameRoom>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
    durableNamespaces: 'GameRoom';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
